services:
  - type: web
    name: hostel-gatepass-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: "your-secret-key"  # Replace with a secure key
