name: Build and Deploy Flask App to Azure Web App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test compilation
        run: python -m compileall .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v1
        with:
          app-name: "hostel-gatepass-system-2024"  # change to match your chosen name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
